name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      # - name: Generate Prisma Client
      #   run: npx prisma generate

      # Optional: Run Prisma Migrate (only if needed, and DB is accessible)
      # - name: Run Prisma Migrate
      #   run: npx prisma migrate deploy
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build project
        run: npm run build

      - name: Zip dist folder
        run: zip -r deploy.zip dist .ebextensions prisma package.json package-lock.json Procfile

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          application_name: reader-hub
          environment_name: Reader-hub-env
          version_label: v-${{ github.sha }}
          
          deployment_package: deploy.zip
